apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - redis.yaml
  - postgresql.yaml
  - immich-server.yaml
  - immich-machine-learning.yaml
  - ingress.yaml

namespace: immich

commonLabels:
  app.kubernetes.io/part-of: immich-stack
