apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis.yaml
  - postgresql.yaml
  - paperless.yaml
  - ingress.yaml

namespace: paperless

commonLabels:
  app.kubernetes.io/part-of: paperless-stack
