apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
  annotations:
    homelab/sync-bump: "2026-02-09"
  labels:
    app.kubernetes.io/name: traefik-system
    app.kubernetes.io/part-of: network-infrastructure